version: "3"

services:
  blog:
    image: ghcr.io/toledompm/post-client:0.6.1
    volumes:
      - ./blog/next.config.js:/app/next.config.js:ro
    ports:
      - 3000:3000
    env_file:
      - blog/.env
  api:
    image: ghcr.io/toledompm/post-api:0.3.0
    ports:
      - 3030:3030
    volumes:
      - ./api/.oci/:/root/.oci/
      - ./api/index/:/root/index/
    env_file:
      - api/.env
